### ISSUE TITLE
Invalid rule: 'http

### ISSUE THREAD

**Issue by geiszla** [lwsjs/redirect#2]
My scripts look like this:

```json
"scripts": {
  "serve": "ws --port 443 --directory build --spa index.html --http2",
  "redirect": "ws --stack redirect --port 8000 --redirect 'http -> https'",
  "prodtest": "concurrently --kill-others \"yarn redirect\" \"yarn serve\""
},
```

When I run `npm redirect` or `npm prodtest`, I get an error:
```sh
Error: Invalid rule: 'http
    at C:\Users\geisz\AppData\Local\Yarn\Data\global\node_modules\lws-redirect\index.js:45:52
    at Array.map (<anonymous>)
    at parseRedirectRules (C:\Users\geisz\AppData\Local\Yarn\Data\global\node_modules\lws-redirect\index.js:42:26)
    at Redirect.middleware (C:\Users\geisz\AppData\Local\Yarn\Data\global\node_modules\lws-redirect\index.js:20:23)
    at C:\Users\geisz\AppData\Local\Yarn\Data\global\node_modules\lws\lib\middleware-stack.js:18:21
    at MiddlewareStack.map (<anonymous>)
    at MiddlewareStack.getMiddlewareFunctions (C:\Users\geisz\AppData\Local\Yarn\Data\global\node_modules\lws\lib\middleware-stack.js:18:8)
    at Lws.useMiddlewareStack (C:\Users\geisz\AppData\Local\Yarn\Data\global\node_modules\lws\index.js:158:36)
    at Function.create (C:\Users\geisz\AppData\Local\Yarn\Data\global\node_modules\lws\index.js:292:9)
    at WsCli.launchServer (C:\Users\geisz\AppData\Local\Yarn\Data\global\node_modules\lws\lib\cli-app.js:180:21)
```

When I copy the script, and run it from the command line it works fine.

The package is installed globally.

**Comment by 75lb** [comment]
does this help? 

https://stackoverflow.com/questions/37500744/how-to-properly-run-a-npm-script-with-arguments

**Comment by 75lb** [comment]
stale - closing.
